
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest
        
      - name: print welcome message
        run: echo 'Welcome to Github Action'
